// animeData.js - Master Anime Catalog for Weebdle
const MASTER_ANIME_DATA = [
  { id: 1, title: "Neon Genesis Evangelion", year: 1995, rank: 215, genres: ["Action", "Drama", "Sci-Fi", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/1314/108941.jpg" },
  { id: 2, title: "Cowboy Bebop", year: 1998, rank: 45, genres: ["Action", "Award Winning", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/4/19644.jpg" },
  { id: 3, title: "Rurouni Kenshin", year: 1996, rank: 360, genres: ["Action", "Adventure", "Romance"], image: "https://img.anili.st/media/45" },
  { id: 4, title: "Berserk (1997)", year: 1997, rank: 98, genres: ["Action", "Adventure", "Drama", "Fantasy", "Supernatural"], image: "https://img.anili.st/media/33" },
  { id: 5, title: "Trigun", year: 1998, rank: 275, genres: ["Action", "Adventure", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/7/20310.jpg" },
  { id: 6, title: "Serial Experiments Lain", year: 1998, rank: 540, genres: ["Drama", "Mystery", "Sci-Fi", "Supernatural"], image: "https://img.anili.st/media/339" },
  { id: 7, title: "Outlaw Star", year: 1998, rank: 1105, genres: ["Action", "Adventure", "Comedy", "Sci-Fi"], image: "https://img.anili.st/media/400" },
  { id: 8, title: "Initial D", year: 1998, rank: 410, genres: ["Action", "Drama"], image: "https://img.anili.st/media/185" },
  { id: 9, title: "Great Teacher Onizuka (GTO)", year: 1999, rank: 50, genres: ["Comedy", "Drama"], image: "https://cdn.myanimelist.net/images/anime/13/11460.jpg" },
  { id: 10, title: "One Piece", year: 1999, rank: 54, genres: ["Action", "Adventure", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/6/73245.jpg" },
  { id: 11, title: "Hunter x Hunter (1999)", year: 1999, rank: 155, genres: ["Action", "Adventure", "Fantasy"], image: "https://img.anili.st/media/136" },
  { id: 12, title: "Yu-Gi-Oh! Duel Monsters", year: 2000, rank: 1720, genres: ["Action", "Adventure", "Fantasy"], image: "https://img.anili.st/media/481" },
  { id: 13, title: "Hajime no Ippo", year: 2000, rank: 48, genres: ["Action", "Comedy", "Sports"], image: "https://cdn.myanimelist.net/images/anime/4/86334.jpg" },
  { id: 14, title: "FLCL", year: 2000, rank: 370, genres: ["Action", "Avant Garde", "Comedy", "Sci-Fi"], image: "https://img.anili.st/media/227" },
  { id: 15, title: "Inuyasha", year: 2000, rank: 740, genres: ["Action", "Adventure", "Fantasy", "Romance"], image: "https://cdn.myanimelist.net/images/anime/2/73862.jpg" },
  { id: 16, title: "Hellsing", year: 2001, rank: 1350, genres: ["Action", "Horror", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/10/19956.jpg" },
  { id: 17, title: "Fruits Basket (2001)", year: 2001, rank: 945, genres: ["Drama", "Romance", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/4/75204.jpg" },
  { id: 18, title: "Shaman King", year: 2001, rank: 1150, genres: ["Action", "Adventure", "Comedy", "Supernatural"], image: "https://img.anili.st/media/154" },
  { id: 19, title: "Naruto", year: 2002, rank: 620, genres: ["Action", "Adventure", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/13/17405.jpg" },
  { id: 20, title: "Ghost in the Shell: Stand Alone Complex", year: 2002, rank: 150, genres: ["Action", "Mystery", "Sci-Fi"], image: "https://img.anili.st/media/467" },
  { id: 21, title: "Fullmetal Alchemist (2003)", year: 2003, rank: 290, genres: ["Action", "Adventure", "Drama", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/10/75815.jpg" },
  { id: 22, title: "Gungrave", year: 2003, rank: 1200, genres: ["Action", "Drama", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/12/22756.jpg" },
  { id: 23, title: "Monster", year: 2004, rank: 5, genres: ["Drama", "Mystery", "Suspense"], image: "https://img.anili.st/media/19" },
  { id: 24, title: "Bleach", year: 2004, rank: 510, genres: ["Action", "Adventure", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/3/40451.jpg" },
  { id: 25, title: "Samurai Champloo", year: 2004, rank: 145, genres: ["Action", "Adventure", "Comedy"], image: "https://img.anili.st/media/205" },
  { id: 26, title: "Elfen Lied", year: 2004, rank: 1120, genres: ["Action", "Drama", "Horror", "Supernatural"], image: "https://img.anili.st/media/226" },
  { id: 27, title: "Eureka Seven", year: 2005, rank: 490, genres: ["Action", "Adventure", "Drama", "Romance", "Sci-Fi"], image: "https://img.anili.st/media/237" },
  { id: 28, title: "Mushishi", year: 2005, rank: 44, genres: ["Adventure", "Fantasy", "Mystery", "Slice of Life"], image: "https://img.anili.st/media/457" },
  { id: 29, title: "Death Note", year: 2006, rank: 78, genres: ["Mystery", "Supernatural", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/1079/138100.jpg" },
  { id: 30, title: "Code Geass: Lelouch of the Rebellion", year: 2006, rank: 52, genres: ["Action", "Drama", "Sci-Fi"], image: "https://img.anili.st/media/1575" },
  { id: 31, title: "Nana", year: 2006, rank: 76, genres: ["Drama", "Romance"], image: "https://cdn.myanimelist.net/images/anime/2/11232.jpg" },
  { id: 32, title: "Black Lagoon", year: 2006, rank: 285, genres: ["Action"], image: "https://img.anili.st/media/889" },
  { id: 33, title: "Ouran High School Host Club", year: 2006, rank: 210, genres: ["Comedy", "Romance"], image: "https://img.anili.st/media/853" },
  { id: 34, title: "The Melancholy of Haruhi Suzumiya", year: 2006, rank: 580, genres: ["Comedy", "Mystery", "Sci-Fi"], image: "https://img.anili.st/media/849" },
  { id: 35, title: "Gintama", year: 2006, rank: 16, genres: ["Action", "Comedy", "Sci-Fi"], image: "https://img.anili.st/media/918" },
  { id: 36, title: "D.Gray-man", year: 2006, rank: 590, genres: ["Action", "Adventure", "Comedy"], image: "https://img.anili.st/media/1482" },
  { id: 37, title: "Fate/stay night", year: 2006, rank: 1680, genres: ["Action", "Fantasy", "Supernatural"], image: "https://img.anili.st/media/356" },
  { id: 38, title: "Higurashi: When They Cry", year: 2006, rank: 495, genres: ["Horror", "Mystery", "Supernatural", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/12/19634.jpg" },
  { id: 39, title: "Tengen Toppa Gurren Lagann", year: 2007, rank: 64, genres: ["Action", "Adventure", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/4/5123.jpg" },
  { id: 40, title: "Clannad", year: 2007, rank: 310, genres: ["Drama", "Romance", "Supernatural"], image: "https://img.anili.st/media/2167" },
  { id: 41, title: "Darker than Black", year: 2007, rank: 380, genres: ["Action", "Mystery", "Sci-Fi"], image: "https://img.anili.st/media/2025" },
  { id: 42, title: "Baccano!", year: 2007, rank: 140, genres: ["Action", "Adventure", "Mystery", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/11/12000.jpg" },
  { id: 43, title: "Claymore", year: 2007, rank: 630, genres: ["Action", "Adventure", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/3/21834.jpg" },
  { id: 44, title: "Soul Eater", year: 2008, rank: 470, genres: ["Action", "Comedy", "Fantasy"], image: "https://img.anili.st/media/3588" },
  { id: 45, title: "Toradora!", year: 2008, rank: 260, genres: ["Drama", "Romance"], image: "https://cdn.myanimelist.net/images/anime/13/22128.jpg" },
  { id: 46, title: "Spice and Wolf", year: 2008, rank: 220, genres: ["Adventure", "Drama", "Fantasy", "Romance"], image: "https://img.anili.st/media/2966" },
  { id: 47, title: "Fullmetal Alchemist: Brotherhood", year: 2009, rank: 2, genres: ["Action", "Adventure", "Drama", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1223/96541.jpg" },
  { id: 48, title: "Bakemonogatari", year: 2009, rank: 165, genres: ["Mystery", "Romance", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/11/75274.jpg" },
  { id: 49, title: "Fairy Tail", year: 2009, rank: 940, genres: ["Action", "Adventure", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/5/18179.jpg" },
  { id: 50, title: "K-On!", year: 2009, rank: 650, genres: ["Comedy", "Slice of Life"], image: "https://cdn.myanimelist.net/images/anime/10/76120.jpg" },
  { id: 51, title: "Durarara!!", year: 2010, rank: 330, genres: ["Action", "Mystery", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/10/71772.jpg" },
  { id: 52, title: "Angel Beats!", year: 2010, rank: 320, genres: ["Action", "Comedy", "Drama", "Supernatural"], image: "https://img.anili.st/media/6547" },
  { id: 53, title: "The Tatami Galaxy", year: 2010, rank: 118, genres: ["Comedy", "Mystery", "Psychological", "Romance"], image: "https://img.anili.st/media/7785" },
  { id: 54, title: "Maid Sama!", year: 2010, rank: 400, genres: ["Comedy", "Romance"], image: "https://img.anili.st/media/7054" },
  { id: 55, title: "Steins;Gate", year: 2011, rank: 3, genres: ["Drama", "Sci-Fi", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/1935/127974.jpg" },
  { id: 56, title: "Hunter x Hunter (2011)", year: 2011, rank: 9, genres: ["Action", "Adventure", "Fantasy"], image: "https://img.anili.st/media/11061" },
  { id: 57, title: "Puella Magi Madoka Magica", year: 2011, rank: 175, genres: ["Drama", "Fantasy", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/11/55225.jpg" },
  { id: 58, title: "Fate/Zero", year: 2011, rank: 130, genres: ["Action", "Fantasy", "Supernatural"], image: "https://img.anili.st/media/10087" },
  { id: 59, title: "Anohana: The Flower We Saw That Day", year: 2011, rank: 240, genres: ["Drama", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/5/79697.jpg" },
  { id: 60, title: "Nichijou - My Ordinary Life", year: 2011, rank: 190, genres: ["Comedy", "Slice of Life"], image: "https://cdn.myanimelist.net/images/anime/3/75617.jpg" },
  { id: 61, title: "Mirai Nikki", year: 2011, rank: 640, genres: ["Action", "Supernatural", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/13/33465.jpg" },
  { id: 62, title: "Guilty Crown", year: 2011, rank: 1210, genres: ["Action", "Drama", "Sci-Fi"], image: "https://img.anili.st/media/10793" },
  { id: 63, title: "Blue Exorcist", year: 2011, rank: 910, genres: ["Action", "Fantasy", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/10/75195.jpg" },
  { id: 64, title: "Chihayafuru", year: 2011, rank: 255, genres: ["Drama", "Sports"], image: "https://img.anili.st/media/10800" },
  { id: 65, title: "Sword Art Online", year: 2012, rank: 1450, genres: ["Action", "Adventure", "Fantasy", "Romance"], image: "https://cdn.myanimelist.net/images/anime/11/39717.jpg" },
  { id: 66, title: "Psycho-Pass", year: 2012, rank: 125, genres: ["Action", "Sci-Fi", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/5/43399.jpg" },
  { id: 67, title: "Shinsekai Yori (From the New World)", year: 2012, rank: 185, genres: ["Drama", "Horror", "Mystery", "Sci-Fi"], image: "https://img.anili.st/media/13125" },
  { id: 68, title: "Hyouka", year: 2012, rank: 280, genres: ["Mystery", "Slice of Life"], image: "https://img.anili.st/media/12189" },
  { id: 69, title: "Kuroko's Basketball", year: 2012, rank: 230, genres: ["Comedy", "Sports"], image: "https://img.anili.st/media/11771" },
  { id: 70, title: "JoJo's Bizarre Adventure (2012)", year: 2012, rank: 210, genres: ["Action", "Adventure", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/3/40409.jpg" },
  { id: 71, title: "The Pet Girl of Sakurasou", year: 2012, rank: 350, genres: ["Comedy", "Drama", "Romance"], image: "https://img.anili.st/media/13759" },
  { id: 72, title: "Magi: The Labyrinth of Magic", year: 2012, rank: 315, genres: ["Action", "Adventure", "Fantasy"], image: "https://img.anili.st/media/14513" },
  { id: 73, title: "Attack on Titan", year: 2013, rank: 110, genres: ["Action", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/10/47347.jpg" },
  { id: 74, title: "Kill la Kill", year: 2013, rank: 270, genres: ["Action", "Comedy", "Ecchi"], image: "https://img.anili.st/media/18679" },
  { id: 75, title: "My Teen Romantic Comedy SNAFU (Oregairu)", year: 2013, rank: 340, genres: ["Comedy", "Romance"], image: "https://cdn.myanimelist.net/images/anime/4/49527.jpg" },
  { id: 76, title: "No Game No Life", year: 2014, rank: 375, genres: ["Comedy", "Fantasy", "Ecchi"], image: "https://cdn.myanimelist.net/images/anime/1074/111944.jpg" },
  { id: 77, title: "Haikyu!!", year: 2014, rank: 95, genres: ["Drama", "Sports"], image: "https://cdn.myanimelist.net/images/anime/7/76014.jpg" },
  { id: 78, title: "Tokyo Ghoul", year: 2014, rank: 820, genres: ["Action", "Horror", "Supernatural", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/1498/134443.jpg" },
  { id: 79, title: "Parasyte -the maxim-", year: 2014, rank: 92, genres: ["Action", "Horror", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/3/73178.jpg" },
  { id: 80, title: "Your Lie in April", year: 2014, rank: 65, genres: ["Drama", "Romance"], image: "https://cdn.myanimelist.net/images/anime/3/67177.jpg" },
  { id: 81, title: "Akame ga Kill!", year: 2014, rank: 880, genres: ["Action", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1429/95946.jpg" },
  { id: 82, title: "Noragami", year: 2014, rank: 450, genres: ["Action", "Supernatural"], image: "https://img.anili.st/media/20447" },
  { id: 83, title: "Terror in Resonance", year: 2014, rank: 420, genres: ["Mystery", "Suspense"], image: "https://img.anili.st/media/20661" },
  { id: 84, title: "Monthly Girls' Nozaki-kun", year: 2014, rank: 430, genres: ["Comedy", "Romance"], image: "https://img.anili.st/media/20668" },
  { id: 85, title: "The Seven Deadly Sins", year: 2014, rank: 890, genres: ["Action", "Adventure", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/8/65409.jpg" },
  { id: 86, title: "One-Punch Man", year: 2015, rank: 112, genres: ["Action", "Comedy", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/12/76049.jpg" },
  { id: 87, title: "Assassination Classroom", year: 2015, rank: 265, genres: ["Action", "Comedy"], image: "https://cdn.myanimelist.net/images/anime/5/75810.jpg" },
  { id: 88, title: "Death Parade", year: 2015, rank: 365, genres: ["Drama", "Supernatural", "Suspense"], image: "https://img.anili.st/media/20931" },
  { id: 89, title: "Food Wars!: Shokugeki no Soma", year: 2015, rank: 295, genres: ["Comedy", "Ecchi"], image: "https://img.anili.st/media/20923" },
  { id: 90, title: "Overlord", year: 2015, rank: 530, genres: ["Action", "Adventure", "Fantasy"], image: "https://img.anili.st/media/20832" },
  { id: 91, title: "Charlotte", year: 2015, rank: 840, genres: ["Drama", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/12/76179.jpg" },
  { id: 92, title: "Erased", year: 2016, rank: 180, genres: ["Mystery", "Supernatural", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/10/77957.jpg" },
  { id: 93, title: "My Hero Academia", year: 2016, rank: 520, genres: ["Action"], image: "https://cdn.myanimelist.net/images/anime/10/78745.jpg" },
  { id: 94, title: "Re:Zero - Starting Life in Another World", year: 2016, rank: 170, genres: ["Drama", "Fantasy", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/11/79410.jpg" },
  { id: 95, title: "Mob Psycho 100", year: 2016, rank: 62, genres: ["Action", "Comedy", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/8/80356.jpg" },
  { id: 96, title: "Konosuba: God's Blessing on this Wonderful World!", year: 2016, rank: 250, genres: ["Adventure", "Comedy", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/8/77831.jpg" },
  { id: 97, title: "Bungo Stray Dogs", year: 2016, rank: 490, genres: ["Action", "Mystery", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/1908/120036.jpg" },
  { id: 98, title: "Yuri!!! on Ice", year: 2016, rank: 660, genres: ["Sports"], image: "https://img.anili.st/media/21709" },
  { id: 99, title: "Made in Abyss", year: 2017, rank: 46, genres: ["Adventure", "Drama", "Fantasy", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/6/86733.jpg" },
  { id: 100, title: "Classroom of the Elite", year: 2017, rank: 600, genres: ["Drama", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/5/86830.jpg" },
  { id: 101, title: "The Ancient Magus' Bride", year: 2017, rank: 415, genres: ["Drama", "Fantasy", "Mythology"], image: "https://img.anili.st/media/98436" },
  { id: 102, title: "Land of the Lustrous", year: 2017, rank: 135, genres: ["Action", "Drama", "Fantasy"], image: "https://img.anili.st/media/98707" },
  { id: 103, title: "Black Clover", year: 2017, rank: 480, genres: ["Action", "Comedy", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/2/88336.jpg" },
  { id: 104, title: "Violet Evergarden", year: 2018, rank: 42, genres: ["Drama", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1795/95088.jpg" },
  { id: 105, title: "Darling in the Franxx", year: 2018, rank: 1190, genres: ["Action", "Drama", "Romance", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/1614/90408.jpg" },
  { id: 106, title: "A Place Further Than the Universe", year: 2018, rank: 85, genres: ["Adventure", "Comedy", "Drama"], image: "https://img.anili.st/media/99426" },
  { id: 107, title: "Devilman Crybaby", year: 2018, rank: 670, genres: ["Action", "Horror", "Supernatural"], image: "https://img.anili.st/media/98460" },
  { id: 108, title: "Grand Blue Dreaming", year: 2018, rank: 120, genres: ["Comedy"], image: "https://img.anili.st/media/100922" },
  { id: 109, title: "That Time I Got Reincarnated as a Slime", year: 2018, rank: 245, genres: ["Action", "Adventure", "Comedy", "Fantasy"], image: "https://img.anili.st/media/101280" },
  { id: 110, title: "Rascal Does Not Dream of Bunny Girl Senpai", year: 2018, rank: 142, genres: ["Drama", "Romance", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/1301/93586.jpg" },
  { id: 111, title: "Banana Fish", year: 2018, rank: 152, genres: ["Action", "Adventure", "Drama", "Suspense"], image: "https://img.anili.st/media/100498" },
  { id: 112, title: "Goblin Slayer", year: 2018, rank: 1050, genres: ["Action", "Adventure", "Fantasy"], image: "https://img.anili.st/media/101165" },
  { id: 113, title: "Dororo", year: 2019, rank: 212, genres: ["Action", "Adventure", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/1879/100467.jpg" },
  { id: 114, title: "The Promised Neverland", year: 2019, rank: 138, genres: ["Mystery", "Sci-Fi", "Suspense"], image: "https://img.anili.st/media/101759" },
  { id: 115, title: "Kaguya-sama: Love Is War", year: 2019, rank: 55, genres: ["Comedy", "Romance"], image: "https://cdn.myanimelist.net/images/anime/1295/106551.jpg" },
  { id: 116, title: "Demon Slayer: Kimetsu no Yaiba", year: 2019, rank: 127, genres: ["Action", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg" },
  { id: 117, title: "Vinland Saga", year: 2019, rank: 35, genres: ["Action", "Adventure", "Drama"], image: "https://cdn.myanimelist.net/images/anime/1500/103005.jpg" },
  { id: 118, title: "Dr. Stone", year: 2019, rank: 235, genres: ["Adventure", "Comedy", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/1613/102576.jpg" },
  { id: 119, title: "Fire Force", year: 2019, rank: 790, genres: ["Action", "Sci-Fi", "Supernatural"], image: "https://img.anili.st/media/105310" },
  { id: 120, title: "Beastars", year: 2019, rank: 550, genres: ["Drama", "Suspense"], image: "https://img.anili.st/media/107660" },
  { id: 121, title: "Dorohedoro", year: 2020, rank: 345, genres: ["Action", "Comedy", "Fantasy", "Horror"], image: "https://img.anili.st/media/105228" },
  { id: 122, title: "Keep Your Hands Off Eizouken!", year: 2020, rank: 440, genres: ["Adventure", "Comedy"], image: "https://img.anili.st/media/109298" },
  { id: 123, title: "Tower of God", year: 2020, rank: 915, genres: ["Action", "Adventure", "Drama", "Fantasy", "Mystery"], image: "https://img.anili.st/media/115230" },
  { id: 124, title: "The God of High School", year: 2020, rank: 2400, genres: ["Action", "Supernatural"], image: "https://img.anili.st/media/116006" },
  { id: 125, title: "Jujutsu Kaisen", year: 2020, rank: 80, genres: ["Action", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg" },
  { id: 126, title: "Rent-a-Girlfriend", year: 2020, rank: 2900, genres: ["Comedy", "Romance"], image: "https://img.anili.st/media/113813" },
  { id: 127, title: "Mushoku Tensei: Jobless Reincarnation", year: 2021, rank: 105, genres: ["Adventure", "Drama", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1530/117776.jpg" },
  { id: 128, title: "Horimiya", year: 2021, rank: 195, genres: ["Romance"], image: "https://cdn.myanimelist.net/images/anime/1695/111486.jpg" },
  { id: 129, title: "86 -Eighty Six-", year: 2021, rank: 89, genres: ["Action", "Drama", "Sci-Fi"], image: "https://img.anili.st/media/116589" },
  { id: 130, title: "Tokyo Revengers", year: 2021, rank: 690, genres: ["Action", "Drama", "Supernatural"], image: "https://img.anili.st/media/120120" },
  { id: 131, title: "To Your Eternity", year: 2021, rank: 218, genres: ["Adventure", "Drama", "Supernatural"], image: "https://img.anili.st/media/114535" },
  { id: 132, title: "Komi Can't Communicate", year: 2021, rank: 610, genres: ["Comedy", "Romance"], image: "https://img.anili.st/media/133965" },
  { id: 133, title: "Ranking of Kings", year: 2021, rank: 93, genres: ["Adventure", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1347/117616.jpg" },
  { id: 134, title: "Blue Period", year: 2021, rank: 545, genres: ["Drama"], image: "https://img.anili.st/media/130664" },
  { id: 135, title: "My Dress-Up Darling", year: 2022, rank: 188, genres: ["Comedy", "Romance"], image: "https://cdn.myanimelist.net/images/anime/1179/119897.jpg" },
  { id: 136, title: "Spy x Family", year: 2022, rank: 114, genres: ["Action", "Comedy"], image: "https://cdn.myanimelist.net/images/anime/1441/122795.jpg" },
  { id: 137, title: "Summer Time Rendering", year: 2022, rank: 94, genres: ["Mystery", "Supernatural", "Suspense"], image: "https://img.anili.st/media/129201" },
  { id: 138, title: "Cyberpunk: Edgerunners", year: 2022, rank: 74, genres: ["Action", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/1818/126435.jpg" },
  { id: 139, title: "Chainsaw Man", year: 2022, rank: 160, genres: ["Action", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg" },
  { id: 140, title: "Blue Lock", year: 2022, rank: 285, genres: ["Sports"], image: "https://cdn.myanimelist.net/images/anime/1258/126929.jpg" },
  { id: 141, title: "Bocchi the Rock!", year: 2022, rank: 25, genres: ["Comedy"], image: "https://cdn.myanimelist.net/images/anime/1448/127956.jpg" },
  { id: 142, title: "Oshi no Ko", year: 2023, rank: 82, genres: ["Drama", "Supernatural"], image: "https://img.anili.st/media/150672" },
  { id: 143, title: "Hell's Paradise", year: 2023, rank: 240, genres: ["Action", "Fantasy", "Supernatural"], image: "https://img.anili.st/media/128893" },
  { id: 144, title: "Heavenly Delusion", year: 2023, rank: 172, genres: ["Adventure", "Mystery", "Sci-Fi"], image: "https://img.anili.st/media/155783" },
  { id: 145, title: "Frieren: Beyond Journey's End", year: 2023, rank: 1, genres: ["Adventure", "Drama", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg" },
  { id: 146, title: "The Apothecary Diaries", year: 2023, rank: 40, genres: ["Drama", "Mystery"], image: "https://cdn.myanimelist.net/images/anime/1708/138033.jpg" },
  { id: 147, title: "Shangri-La Frontier", year: 2023, rank: 380, genres: ["Action", "Adventure", "Fantasy"], image: "https://img.anili.st/media/151970" },
  { id: 148, title: "Undead Unluck", year: 2023, rank: 620, genres: ["Action", "Comedy", "Supernatural"], image: "https://img.anili.st/media/154116" },
  { id: 149, title: "Delicious in Dungeon", year: 2024, rank: 115, genres: ["Adventure", "Comedy", "Fantasy"], image: "https://img.anili.st/media/153518" },
  { id: 150, title: "Solo Leveling", year: 2024, rank: 250, genres: ["Action", "Adventure", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1370/140362.jpg" },
  { id: 151, title: "Kaiju No. 8", year: 2024, rank: 310, genres: ["Action", "Sci-Fi"], image: "https://img.anili.st/media/153288" },
  { id: 152, title: "Wind Breaker", year: 2024, rank: 450, genres: ["Action"], image: "https://img.anili.st/media/163270" },
  { id: 153, title: "Dandadan", year: 2024, rank: 85, genres: ["Action", "Comedy", "Supernatural"], image: "https://img.anili.st/media/171018" },
  { id: 154, title: "Sakamoto Days", year: 2025, rank: 190, genres: ["Action", "Comedy"], image: "https://img.anili.st/media/177770" },
  { id: 155, title: "The Dangers in My Heart", year: 2023, rank: 68, genres: ["Comedy", "Romance"], image: "https://img.anili.st/media/153152" },
  { id: 156, title: "Pluto", year: 2023, rank: 90, genres: ["Action", "Mystery", "Sci-Fi", "Suspense"], image: "https://img.anili.st/media/99088" },
  { id: 157, title: "Orb: On the Movements of the Earth", year: 2024, rank: 130, genres: ["Drama", "Historical"], image: "https://img.anili.st/media/151475" },
  { id: 158, title: "Cardcaptor Sakura", year: 1998, rank: 260, genres: ["Adventure", "Comedy", "Fantasy", "Romance"], image: "https://img.anili.st/media/232" },
  { id: 159, title: "Perfect Blue", year: 1998, rank: 71, genres: ["Avant Garde", "Drama", "Horror", "Suspense"], image: "https://img.anili.st/media/437" },
  { id: 160, title: "Princess Mononoke", year: 1997, rank: 33, genres: ["Action", "Adventure", "Award Winning", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/7/75919.jpg" },
  { id: 161, title: "Spirited Away", year: 2001, rank: 30, genres: ["Adventure", "Award Winning", "Supernatural"], image: "https://img.anili.st/media/199" },
  { id: 162, title: "Howl's Moving Castle", year: 2004, rank: 77, genres: ["Adventure", "Award Winning", "Drama", "Fantasy"], image: "https://img.anili.st/media/431" },
  { id: 163, title: "Revolutionary Girl Utena", year: 1997, rank: 390, genres: ["Drama", "Fantasy", "Mystery"], image: "https://img.anili.st/media/440" },
  { id: 164, title: "The Vision of Escaflowne", year: 1996, rank: 720, genres: ["Adventure", "Fantasy", "Romance", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/11/38479.jpg" },
  { id: 165, title: "Slayers", year: 1995, rank: 860, genres: ["Adventure", "Comedy", "Fantasy"], image: "https://img.anili.st/media/534" },
  { id: 166, title: "Martian Successor Nadesico", year: 1996, rank: 1110, genres: ["Action", "Comedy", "Sci-Fi"], image: "https://img.anili.st/media/218" },
  { id: 167, title: "Golden Boy", year: 1995, rank: 305, genres: ["Adventure", "Comedy", "Ecchi"], image: "https://img.anili.st/media/268" },
  { id: 168, title: "Mobile Suit Gundam Wing", year: 1995, rank: 1180, genres: ["Action", "Drama", "Sci-Fi"], image: "https://img.anili.st/media/90" },
  { id: 169, title: "Mobile Suit Gundam 00", year: 2007, rank: 360, genres: ["Action", "Drama", "Sci-Fi"], image: "https://img.anili.st/media/2581" },
  { id: 170, title: "Mobile Suit Gundam: Iron-Blooded Orphans", year: 2015, rank: 312, genres: ["Action", "Drama", "Sci-Fi"], image: "https://img.anili.st/media/21268" },
  { id: 171, title: "Mobile Suit Gundam: The Witch from Mercury", year: 2022, rank: 530, genres: ["Action", "Sci-Fi"], image: "https://img.anili.st/media/139274" },
  { id: 172, title: "Gankutsuou: The Count of Monte Cristo", year: 2004, rank: 265, genres: ["Drama", "Mystery", "Sci-Fi", "Suspense"], image: "https://img.anili.st/media/239" },
  { id: 173, title: "Ergo Proxy", year: 2006, rank: 460, genres: ["Mystery", "Sci-Fi"], image: "https://img.anili.st/media/790" },
  { id: 174, title: "Wolf's Rain", year: 2003, rank: 580, genres: ["Action", "Adventure", "Drama", "Sci-Fi"], image: "https://img.anili.st/media/202" },
  { id: 175, title: "Paranoia Agent", year: 2004, rank: 640, genres: ["Avant Garde", "Drama", "Mystery", "Suspense"], image: "https://img.anili.st/media/323" },
  { id: 176, title: "Paprika", year: 2006, rank: 300, genres: ["Avant Garde", "Fantasy", "Mystery", "Sci-Fi", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/12/37525.jpg" },
  { id: 177, title: "The Girl Who Leapt Through Time", year: 2006, rank: 198, genres: ["Award Winning", "Drama", "Sci-Fi"], image: "https://img.anili.st/media/2236" },
  { id: 178, title: "Summer Wars", year: 2009, rank: 385, genres: ["Award Winning", "Comedy", "Sci-Fi"], image: "https://cdn.myanimelist.net/images/anime/11/75276.jpg" },
  { id: 179, title: "Wolf Children", year: 2012, rank: 63, genres: ["Award Winning", "Drama", "Fantasy", "Slice of Life"], image: "https://cdn.myanimelist.net/images/anime/9/35721.jpg" },
  { id: 180, title: "Your Name.", year: 2016, rank: 11, genres: ["Award Winning", "Drama", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/5/87048.jpg" },
  { id: 181, title: "Weathering with You", year: 2019, rank: 180, genres: ["Award Winning", "Drama", "Fantasy", "Romance"], image: "https://cdn.myanimelist.net/images/anime/1880/101146.jpg" },
  { id: 182, title: "Suzume", year: 2022, rank: 210, genres: ["Adventure", "Fantasy"], image: "https://img.anili.st/media/143270" },
  { id: 183, title: "A Silent Voice", year: 2016, rank: 19, genres: ["Award Winning", "Drama"], image: "https://img.anili.st/media/20954" },
  { id: 184, title: "I Want to Eat Your Pancreas", year: 2018, rank: 58, genres: ["Drama", "Romance"], image: "https://img.anili.st/media/99750" },
  { id: 185, title: "Josee, the Tiger and the Fish", year: 2020, rank: 112, genres: ["Drama", "Romance"], image: "https://img.anili.st/media/113596" },
  { id: 186, title: "Look Back", year: 2024, rank: 22, genres: ["Award Winning", "Drama"], image: "https://img.anili.st/media/175510" },
  { id: 187, title: "The Boy and the Heron", year: 2023, rank: 210, genres: ["Adventure", "Award Winning", "Fantasy"], image: "https://img.anili.st/media/100298" },
  { id: 188, title: "Redline", year: 2009, rank: 232, genres: ["Action", "Sci-Fi"], image: "https://img.anili.st/media/6675" },
  { id: 189, title: "Promare", year: 2019, rank: 480, genres: ["Action", "Sci-Fi"], image: "https://img.anili.st/media/100663" },
  { id: 190, title: "Akira", year: 1988, rank: 285, genres: ["Action", "Award Winning", "Sci-Fi", "Suspense"], image: "https://img.anili.st/media/47" },
  { id: 191, title: "Ghost in the Shell (1995)", year: 1995, rank: 135, genres: ["Action", "Award Winning", "Mystery", "Sci-Fi", "Suspense"], image: "https://img.anili.st/media/43" },
  { id: 192, title: "Vampire Hunter D: Bloodlust", year: 2000, rank: 540, genres: ["Action", "Fantasy", "Horror", "Sci-Fi"], image: "https://img.anili.st/media/543" },
  { id: 193, title: "Lucky Star", year: 2007, rank: 690, genres: ["Comedy"], image: "https://img.anili.st/media/1887" },
  { id: 194, title: "Daily Lives of High School Boys", year: 2012, rank: 148, genres: ["Comedy"], image: "https://cdn.myanimelist.net/images/anime/12/35925.jpg" },
  { id: 195, title: "Haven't You Heard? I'm Sakamoto", year: 2016, rank: 1200, genres: ["Comedy"], image: "https://img.anili.st/media/21595" },
  { id: 196, title: "The Disastrous Life of Saiki K.", year: 2016, rank: 88, genres: ["Comedy", "Supernatural"], image: "https://img.anili.st/media/21804" },
  { id: 197, title: "Hinamatsuri", year: 2018, rank: 245, genres: ["Comedy", "Sci-Fi", "Supernatural"], image: "https://img.anili.st/media/100077" },
  { id: 198, title: "Asobi Asobase", year: 2018, rank: 260, genres: ["Comedy"], image: "https://img.anili.st/media/101001" },
  { id: 199, title: "Mashle: Magic and Muscles", year: 2023, rank: 820, genres: ["Action", "Comedy", "Fantasy"], image: "https://img.anili.st/media/151801" },
  { id: 200, title: "Highschool of the Dead", year: 2010, rank: 1540, genres: ["Action", "Ecchi", "Horror", "Supernatural"], image: "https://img.anili.st/media/8074" },
  { id: 201, title: "High School DxD", year: 2012, rank: 1100, genres: ["Action", "Comedy", "Ecchi", "Fantasy", "Romance"], image: "https://img.anili.st/media/11617" },
  { id: 202, title: "Date A Live", year: 2013, rank: 1520, genres: ["Fantasy", "Romance", "Sci-Fi"], image: "https://img.anili.st/media/15583" },
  { id: 203, title: "Chivalry of a Failed Knight", year: 2015, rank: 710, genres: ["Action", "Fantasy", "Romance"], image: "https://img.anili.st/media/21092" },
  { id: 204, title: "Prison School", year: 2015, rank: 560, genres: ["Comedy", "Ecchi"], image: "https://img.anili.st/media/20807" },
  { id: 205, title: "Golden Kamuy", year: 2018, rank: 370, genres: ["Action", "Adventure"], image: "https://img.anili.st/media/99699" },
  { id: 206, title: "Kingdom", year: 2012, rank: 380, genres: ["Action"], image: "https://img.anili.st/media/12031" },
  { id: 207, title: "Megalo Box", year: 2018, rank: 410, genres: ["Action", "Drama", "Sci-Fi", "Sports"], image: "https://img.anili.st/media/100295" },
  { id: 208, title: "Kaiji: Ultimate Survivor", year: 2007, rank: 175, genres: ["Suspense"], image: "https://img.anili.st/media/3002" },
  { id: 209, title: "One Outs", year: 2008, rank: 155, genres: ["Sports", "Suspense"], image: "https://img.anili.st/media/5040" },
  { id: 210, title: "Diamond no Ace", year: 2013, rank: 255, genres: ["Sports"], image: "https://img.anili.st/media/18689" },
  { id: 211, title: "Slam Dunk", year: 1993, rank: 96, genres: ["Sports"], image: "https://img.anili.st/media/170" },
  { id: 212, title: "Ping Pong the Animation", year: 2014, rank: 51, genres: ["Award Winning", "Drama", "Sports"], image: "https://img.anili.st/media/20607" },
  { id: 213, title: "Run with the Wind", year: 2018, rank: 87, genres: ["Drama", "Sports"], image: "https://img.anili.st/media/101903" },
  { id: 214, title: "Sk8 the Infinity", year: 2021, rank: 540, genres: ["Sports"], image: "https://img.anili.st/media/124153" },
  { id: 215, title: "Aoashi", year: 2022, rank: 330, genres: ["Sports"], image: "https://img.anili.st/media/134732" },
  { id: 216, title: "Digimon Adventure", year: 1999, rank: 820, genres: ["Adventure", "Fantasy"], image: "https://img.anili.st/media/552" },
  { id: 217, title: "Katekyo Hitman Reborn!", year: 2006, rank: 325, genres: ["Action", "Comedy"], image: "https://img.anili.st/media/1604" },
  { id: 218, title: "World Trigger", year: 2014, rank: 740, genres: ["Action", "Sci-Fi"], image: "https://img.anili.st/media/20729" },
  { id: 219, title: "Moriarty the Patriot", year: 2020, rank: 250, genres: ["Mystery", "Suspense"], image: "https://img.anili.st/media/114124" },
  { id: 220, title: "Blood Blockade Battlefront", year: 2015, rank: 615, genres: ["Action", "Comedy", "Supernatural"], image: "https://img.anili.st/media/20727" },
  { id: 221, title: "91 Days", year: 2016, rank: 410, genres: ["Action", "Drama", "Suspense"], image: "https://img.anili.st/media/21679" },
  { id: 222, title: "Lycoris Recoil", year: 2022, rank: 340, genres: ["Action"], image: "https://img.anili.st/media/147048" },
  { id: 223, title: "Girls und Panzer", year: 2012, rank: 910, genres: ["Action", "Sports"], image: "https://img.anili.st/media/14131" },
  { id: 224, title: "Uma Musume: Pretty Derby", year: 2018, rank: 1150, genres: ["Sports"], image: "https://img.anili.st/media/98514" },
  { id: 225, title: "Fate/stay night: Unlimited Blade Works", year: 2014, rank: 97, genres: ["Action", "Fantasy", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/12/67333.jpg" },
  { id: 226, title: "Kara no Kyoukai", year: 2007, rank: 140, genres: ["Action", "Mystery", "Supernatural", "Suspense"], image: "https://img.anili.st/media/2593" },
  { id: 227, title: "Log Horizon", year: 2013, rank: 420, genres: ["Action", "Adventure", "Fantasy"], image: "https://img.anili.st/media/17265" },
  { id: 228, title: "The Saga of Tanya the Evil", year: 2017, rank: 395, genres: ["Action", "Fantasy"], image: "https://img.anili.st/media/21613" },
  { id: 229, title: "The Rising of the Shield Hero", year: 2019, rank: 480, genres: ["Action", "Adventure", "Drama", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1490/101365.jpg" },
  { id: 230, title: "The Eminence in Shadow", year: 2022, rank: 135, genres: ["Action", "Comedy", "Fantasy"], image: "https://cdn.myanimelist.net/images/anime/1874/121869.jpg" },
  { id: 231, title: "Ascendance of a Bookworm", year: 2019, rank: 320, genres: ["Fantasy"], image: "https://img.anili.st/media/108268" },
  { id: 232, title: "Clannad: After Story", year: 2008, rank: 14, genres: ["Drama", "Romance", "Supernatural"], image: "https://cdn.myanimelist.net/images/anime/1299/110774.jpg" },
  { id: 233, title: "Plastic Memories", year: 2015, rank: 445, genres: ["Drama", "Romance", "Sci-Fi"], image: "https://img.anili.st/media/20872" },
  { id: 234, title: "Golden Time", year: 2013, rank: 540, genres: ["Comedy", "Drama", "Romance"], image: "https://cdn.myanimelist.net/images/anime/12/52091.jpg" },
  { id: 235, title: "Kokoro Connect", year: 2012, rank: 580, genres: ["Drama", "Romance", "Supernatural"], image: "https://img.anili.st/media/11887" },
  { id: 236, title: "Orange", year: 2016, rank: 690, genres: ["Drama", "Romance", "Sci-Fi"], image: "https://img.anili.st/media/21647" },
  { id: 237, title: "ReLIFE", year: 2016, rank: 260, genres: ["Drama", "Romance"], image: "https://img.anili.st/media/21049" },
  { id: 238, title: "Tsuki ga Kirei", year: 2017, rank: 395, genres: ["Romance"], image: "https://img.anili.st/media/98202" },
  { id: 239, title: "The Angel Next Door Spoils Me Rotten", year: 2023, rank: 380, genres: ["Romance"], image: "https://img.anili.st/media/143338" },
  { id: 240, title: "Insomniacs After School", year: 2023, rank: 215, genres: ["Romance"], image: "https://img.anili.st/media/143653" },
  { id: 241, title: "Blue Box", year: 2024, rank: 160, genres: ["Romance", "Sports"], image: "https://img.anili.st/media/170881" },
  { id: 242, title: "Kimi ni Todoke", year: 2009, rank: 310, genres: ["Drama", "Romance"], image: "https://img.anili.st/media/6045" },
  { id: 243, title: "Kamisama Kiss", year: 2012, rank: 240, genres: ["Comedy", "Fantasy", "Romance", "Supernatural"], image: "https://img.anili.st/media/14713" },
  { id: 244, title: "Yona of the Dawn", year: 2014, rank: 230, genres: ["Action", "Adventure", "Fantasy", "Romance"], image: "https://img.anili.st/media/20770" },
  { id: 245, title: "My Happy Marriage", year: 2023, rank: 310, genres: ["Drama", "Fantasy", "Romance"], image: "https://img.anili.st/media/147103" },
  { id: 246, title: "Mononoke", year: 2007, rank: 165, genres: ["Fantasy", "Horror", "Mystery", "Supernatural"], image: "https://img.anili.st/media/2246" },
  { id: 247, title: "Shiki", year: 2010, rank: 490, genres: ["Horror", "Mystery", "Supernatural", "Suspense"], image: "https://img.anili.st/media/7724" },
  { id: 248, title: "Another", year: 2012, rank: 870, genres: ["Horror", "Mystery", "Supernatural", "Suspense"], image: "https://cdn.myanimelist.net/images/anime/4/75509.jpg" },
  { id: 249, title: "Deadman Wonderland", year: 2011, rank: 1350, genres: ["Action", "Horror", "Sci-Fi", "Suspense"], image: "https://img.anili.st/media/6880" },
  { id: 250, title: "Kakegurui", year: 2017, rank: 1200, genres: ["Drama", "Mystery", "Suspense"], image: "https://img.anili.st/media/98314" }
];
